name: test

on: workflow_dispatch

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test

    # Configure Git informations
      - name: Configure Git informations
        run: |
          git config --global user.name $GITHUB_ACTOR
          git config --global user.email $GITHUB_ACTOR@users.noreply.github.com

      - name: Push new artifacts into branch
        run: |
          mkdir DEPLOYING
          mv .git DEPLOYING/.git
          mv out DEPLOYING/out
          echo "Pushing build to main"
          mv .git DEPLOYING/.git
          cd DEPLOYING
          git add -A
          git commit -m "Automated build"
          git push origin stevo45/test-workflow
          cd ..